library(datasets)
full <- read.csv2("household_power_consumption.txt", header = T, sep = ";", na.strings = "?", colClasses=c(rep("character",9)))
needed <- subset(full, Date == "1/2/2007" | Date == "2/2/2007")
needed$datetime <- strptime(paste(needed$Date,needed$Time),"%d/%m/%Y %H:%M:%S")
png("plot3.png",width = 480, height = 480, units = "px")
plot(needed$datetime,needed$Sub_metering_1,ylab="Energy sub metering",type="s",col="black",xlab="")
lines(needed$datetime,needed$Sub_metering_2,ylab="Energy sub metering",type="s",col="red")
lines(needed$datetime,needed$Sub_metering_3,ylab="Energy sub metering",type="s",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1,cex=0.8)
#dev.copy(png,file="plot3.png"width = 480, height = 480, units = "px", pointsize = 12)
dev.off()